### PR TITLE
Port Leaderboard from Flask -> Django

### PR DESCRIPTION
**Pull request by igniteflow**

### CODE REVIEW

**Comment by dannymilsom** [comment]
@igniteflow Thanks for that Phil!

I've tweaked a couple of things in `igniteflow-leaderboard` - main thing being we no longer have a users list JSON file / try and fetch that data from the slack API directly. Instead the `Player` model now stores the `real_name` field (although I need to add a migration for that when I get chance).

Everything seemed to load fine locally though - maybe take a look and if it looks good I'll merge that branch in (which has everything from your remote branch on plus my tweaks)

**Comment by igniteflow** [comment]
Thanks for looking at this @dannymilsom - tweaks look good!  It's nice to be able to remove the Slack API call and just fetch the data from one place.  I've made a minor change to the README which might be worth including.  Minor background story: The caching object was originally an in-memory cache as it was a single Flask instance, if you were wondering about the slightly odd setup - I moved it to memcache when porting to Appengine.

**Comment by dannymilsom** [comment]
Nice! To be fair it might actually be worth adding the slack API key so we can poll the slack API for any changes to the users - as currently I think once a player is created their attributes aren't modified - but I can add that back in a different ticket.

I'll add the little migration today then merge it all in!

**Comment by dannymilsom** [comment]
@igniteflow I've added a task for the migration - see https://github.com/dannymilsom/poolbot-server/commit/d9ea56f82513f66a7e265920f62cfbcde2ed7326 - and merged this all in.

Thanks mate!

**Pull request merged**
